version: '3'

services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    env_file:
      - csvserver.env
    volumes:
      - ./inputFile:/csvserver/inputdata
    ports:
      - "9393:9300"
    restart: always

