version: '3'

services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    env_file:
      - csvserver.env
    volumes:
      - ./inputFile:/csvserver/inputdata
    ports:
      - "9393:9300"
    restart: always
  prometheus:
    image: prom/prometheus:v2.22.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
